[build]
  command = "npm run build"
  functions = "functions" # Netlify 서버리스 함수가 작성된 디렉토리를 지정합니다.
  publish = "dist"  # 프로젝트 빌드 경과의 디렉토리를 지정합니다.

[dev]
    framework = "#custom"
    command = "npm run dev:webpack"
    targetPort = 8079 # 연결할 프로젝트 개발 서버의 포트 지정
    port = 8080 # 출력할 Netlify 서버의 포트를 지정
    publish = "dist"
    autoLaunch = false